"""Add is_approved column to users

Revision ID: c4d0b78d317f
Revises: c61598bf93fb
Create Date: 2024-12-22 10:32:01.180081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d0b78d317f'
down_revision: Union[str, None] = 'c61598bf93fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#
# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
#     # ### end Alembic commands ###
#
#
# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('users', 'is_approved')
#     # ### end Alembic commands ###
