"""Add first_login column to users

Revision ID: e1eb01d9e86a
Revises: c4d0b78d317f
Create Date: 2024-12-22 10:50:19.098415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1eb01d9e86a'
down_revision: Union[str, None] = 'c4d0b78d317f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_first_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_first_login')
    # ### end Alembic commands ###
